export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const CREATE_OBJECTION_BEGIN = "CREATE_OBJECTION_BEGIN";
export const CREATE_OBJECTION_SUCCES = "CREATE_OBJECTION_SUCCES";
export const CREATE_OBJECTION_ERROR = "CREATE_OBJECTION_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const DELETE_USER_BEGIN = "DELETE_USER_BEGIN";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const DELETE_OBJECTION_BEGIN = "DELETE_OBJECTION_BEGIN";
export const DELETE_OBJECTION_SUCCES = "DELETE_OBJECTION_SUCCES";
export const DELETE_OBJECTION_ERROR = "DELETE_OBJECTION_ERROR";

export const GET_OBJECTIONS_BEGIN = "GET_OBJECTIONS_BEGIN";
export const GET_OBJECTIONS_SUCCESS = "GET_OBJECTIONS_SUCCESS";
export const GET_OBJECTIONS_ERROR = "GET_OBJECTIONS_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

// ratings
export const CREATE_RATING_BEGIN = "CREATE_RATING_BEGIN";
export const CREATE_RATING_SUCCESS = "CREATE_RATING_SUCCESS";
export const CREATE_RATING_ERROR = "CREATE_RATING_ERROR";

export const GET_RATING_BEGIN = "GET_RATING_BEGIN";
export const GET_RATING_SUCCESS = "GET_RATING_SUCCESS";
export const GET_RATING_ERROR = "GET_RATING_ERROR";
