export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const DISPLAY_MODAL = "SHOW_MODAL";
export const CLEAR_MODAL = "CLEAR_MODAL";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const CREATE_OBJECTION_BEGIN = "CREATE_OBJECTION_BEGIN";
export const CREATE_OBJECTION_SUCCES = "CREATE_OBJECTION_SUCCES";
export const CREATE_OBJECTION_ERROR = "CREATE_OBJECTION_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const DELETE_USER_BEGIN = "DELETE_USER_BEGIN";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const DELETE_OBJECTION_BEGIN = "DELETE_OBJECTION_BEGIN";
export const DELETE_OBJECTION_SUCCESS = "DELETE_OBJECTION_SUCCESS";
export const DELETE_OBJECTION_ERROR = "DELETE_OBJECTION_ERROR";

export const GET_OBJECTIONS_BEGIN = "GET_OBJECTIONS_BEGIN";
export const GET_OBJECTIONS_SUCCESS = "GET_OBJECTIONS_SUCCESS";
export const GET_OBJECTIONS_ERROR = "GET_OBJECTIONS_ERROR";

export const UPDATE_OBJECTION_BEGIN = "UPDATE_OBJECTION_BEGIN";
export const UPDATE_OBJECTION_SUCCESS = "UPDATE_OBJECTION_SUCCESS";
export const UPDATE_OBJECTION_ERROR = "UPDATE_OBJECTION_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

// ratings
export const CREATE_RATING_BEGIN = "CREATE_RATING_BEGIN";
export const CREATE_RATING_SUCCESS = "CREATE_RATING_SUCCESS";
export const CREATE_RATING_ERROR = "CREATE_RATING_ERROR";

export const GET_RATING_BEGIN = "GET_RATING_BEGIN";
export const GET_RATING_SUCCESS = "GET_RATING_SUCCESS";
export const GET_RATING_ERROR = "GET_RATING_ERROR";
 //for a referee ratings
export const GET_ALLRATING_BEGIN = "GET_ALLRATING_BEGIN";
export const GET_ALLRATING_SUCCESS = "GET_ALLRATING_SUCCESS";
export const GET_ALLRATING_ERROR = "GET_ALLRATING_ERROR";

// referees
export const GET_REFEREES_BEGIN = "GET_REFEREES_BEGIN";
export const GET_REFEREES_SUCCESS = "GET_REFEREES_SUCCESS";
// export const GET_REFEREES_ERROR = "GET_REFEREES_ERROR";

export const GET_REFEREE_BEGIN = "GET_REFEREE_BEGIN";
export const GET_REFEREE_SUCCESS = "GET_REFEREE_SUCCESS";
export const GET_REFEREE_ERROR = "GET_REFEREE_ERROR";

export const GET_REFEREE_RATINGS_BEGIN = "GET_REFEREE_RATINGS_BEGIN";
export const GET_REFEREE_RATINGS_SUCCESS = "GET_REFEREE_RATINGS_SUCCESS";
export const GET_REFEREE_RATINGS_ERROR = "GET_REFEREE_RATINGS_ERROR";

export const GET_REFEREES_RATINGS_BEGIN = "GET_REFEREES_RATINGS_BEGIN";
export const GET_REFEREES_RATINGS_SUCCESS = "GET_REFEREES_RATINGS_SUCCESS";
export const GET_REFEREES_RATINGS_ERROR = "GET_REFEREES_RATINGS_ERROR";

export const GET_DUE_REPORTS_BEGIN = "GET_REPORTS_BEGIN";
export const GET_DUE_REPORTS_SUCCESS = "GET_REPORTS_SUCCESS";

export const SET_EDIT_REPORT = "SET_EDIT_REPORT";

export const EDIT_REPORT_BEGIN = "EDIT_REPORT_BEGIN";
export const EDIT_REPORT_SUCCESS = "EDIT_REPORT_SUCCESS";
export const EDIT_REPORT_ERROR = "EDIT_REPORT_ERROR";

export const SEND_VERIFY_EMAIL_BEGIN = "SEND_VERIFY_EMAIL_BEGIN";
export const SEND_VERIFY_EMAIL_SUCCESS = "SEND_VERIFY_EMAIL_SUCCESS";
export const SEND_VERIFY_EMAIL_ERROR = "SEND_VERIFY_EMAIL_ERROR";

export const VERIFY_USER_BEGIN = "VERIFY_USER_BEGIN";
export const VERIFY_USER_SUCCESS = "VERIFY_USER_SUCCESS";
export const VERIFY_USER_ERROR = "VERIFY_USER_ERROR";
